import { images } from "@/images/images";
import { StaticImageData } from "next/image";

export const NairobiAreas = [
  "Roysambu",
  "Kahawa West",
  "Kahawa Sukari",
  "Kahawa Wendani",
  "Zimmerman",
  "Githurai 44",
  "Githurai 45",
  "Ruiru",
  "Ruaka",
  "Westlands",
  "Parklands",
  "Kileleshwa",
  "Lavington",
  "Kilimani",
  "Hurlingham",
  "Ngong Road",
  "Dagoretti",
  "Karen",
  "Lang'ata",
  "Ongata Rongai",
  "Kiserian",
  "Embakasi",
  "Embakasi East",
  "Imara Daima",
  "Pipeline",
  "Umoja",
  "Umoja Innercore",
  "Donholm",
  "Savannah",
  "Tena",
  "Kayole",
  "Komarock",
  "Buruburu",
  "Madaraka",
  "South B",
  "South C",
  "Nyayo Estate",
  "Utawala",
  "Mlolongo",
  "Kitengela", // technically Kajiado County but commonly grouped due to proximity
  "Syokimau",
  "Athi River",
  "Thome",
  "Garden Estate",
  "Muthaiga",
  "Runda",
  "Gigiri",
  "Loresho",
  "Mountain View",
  "Kawangware",
  "Kibra",
  "Highrise",
  "Eastleigh",
  "Pangani",
  "Mlango Kubwa",
  "Mathare",
  "Kariobangi",
  "Dandora",
  "Huruma",
  "Lucky Summer",
  "Baba Dogo",
  "Ngara",
  "Kenyatta Market",
];

export const topTenModels: Model[] = [
  {
    id: 1,
    name: "Tess",
    image: images.Image1,
    rating: 4.5,
    location: "Roysambu",
    age: 22,
    height: "5ft 10in",
    bodyType: "Hourglass",
    skinTone: "Fair",
    ethnicity: "African",
    phone: "0712345678",
    modelLevel: "VIP",
    reviews: 100,
    priceInCall: 100,
    priceOutCall: 120,
    servicesOffered: [
      "OWO (Oral without condom)",
      "O-Level (Oral sex)",
      "CIM (Come in mouth)",
      "COF (Come on face)",
      "COB (Come on body)",
      "Swallow",
      "DFK (deep French kissing)",
      "A-Level (Anal sex)",
      "Anal Rimming (analingus)",
      "69 (69 sex position) - Reverse oral & face sitting",
      "Striptease - lap dance & spanking",
      "Erotic massage (incl. Nuru)",
      "Golden shower (Watersports)",
      "Couples (Group sex)",
      // "GFE (Girlfriend experience)",
      // "Threesome",
      // "Fetishism",
      // "Sex toys & Dildo vibrators",
    ],
    description:
      "I'm 24 years old, simple and natural girl, with a body that is voluptuous and curvy, and a personality that is charming and passionate. I came very recently into this field in order to supplement my earnings. When it comes to the integrity of my service, I ensure that you are fully satisfied, where you can freely communicate your needs, based on which I can customise our session. ADVANCE PAYMENT IS MANDATORY FOR VIDEO CALL VERIFICATION WITHOUT ADVANCE DON'T ASK VIDEO CALL VERIFICATION, PLEASE.",
  },
  {
    id: 2,
    name: "Nadia",
    image: images.Image2,
    rating: 4.8,
    location: "Kilimani",
    age: 24,
    height: "5ft 8in",
    bodyType: "Slim",
    skinTone: "Caramel",
    ethnicity: "African",
    phone: "0798456123",
    modelLevel: "Elite",
    reviews: 215,
    priceInCall: 150,
    priceOutCall: 170,
    servicesOffered: [
      "OWO (Oral without condom)",
      "O-Level (Oral sex)",
      "CIM (Come in mouth)",
      "COF (Come on face)",
      "COB (Come on body)",
      "Swallow",
      "DFK (deep French kissing)",
      "A-Level (Anal sex)",
      "Anal Rimming (analingus)",
      "69 (69 sex position) - Reverse oral & face sitting",
      "Striptease - lap dance & spanking",
      "Erotic massage (incl. Nuru)",
      "Golden shower (Watersports)",
      "Couples (Group sex)",
      "GFE (Girlfriend experience)",
      "Threesome",
      "Fetishism",
      "Sex toys & Dildo vibrators",
    ],
    description:
      "I'm 24 years old, simple and natural girl, with a body that is voluptuous and curvy, and a personality that is charming and passionate. I came very recently into this field in order to supplement my earnings. When it comes to the integrity of my service, I ensure that you are fully satisfied, where you can freely communicate your needs, based on which I can customise our session. ADVANCE PAYMENT IS MANDATORY FOR VIDEO CALL VERIFICATION WITHOUT ADVANCE DON'T ASK VIDEO CALL VERIFICATION, PLEASE.",
  },
  {
    id: 3,
    name: "Keisha",
    image: images.Image3,
    rating: 4.7,
    location: "Westlands",
    age: 26,
    height: "5ft 7in",
    bodyType: "Athletic",
    skinTone: "Dark",
    ethnicity: "African",
    phone: "0709456123",
    modelLevel: "Premium",
    reviews: 176,
    priceInCall: 120,
    priceOutCall: 140,
    servicesOffered: [
      "OWO (Oral without condom)",
      "O-Level (Oral sex)",
      "CIM (Come in mouth)",
      "COF (Come on face)",
      "COB (Come on body)",
      "Swallow",
      "DFK (deep French kissing)",
      "A-Level (Anal sex)",
      "Anal Rimming (analingus)",
      "69 (69 sex position) - Reverse oral & face sitting",
      "Striptease - lap dance & spanking",
      "Erotic massage (incl. Nuru)",
      "Golden shower (Watersports)",
      "Couples (Group sex)",
      "GFE (Girlfriend experience)",
      "Threesome",
      "Fetishism",
      "Sex toys & Dildo vibrators",
    ],
    description:
      "I'm 24 years old, simple and natural girl, with a body that is voluptuous and curvy, and a personality that is charming and passionate. I came very recently into this field in order to supplement my earnings. When it comes to the integrity of my service, I ensure that you are fully satisfied, where you can freely communicate your needs, based on which I can customise our session. ADVANCE PAYMENT IS MANDATORY FOR VIDEO CALL VERIFICATION WITHOUT ADVANCE DON'T ASK VIDEO CALL VERIFICATION, PLEASE.",
  },
  {
    id: 4,
    name: "Amina",
    image: images.Image4,
    rating: 4.6,
    location: "Parklands",
    age: 23,
    height: "5ft 6in",
    bodyType: "Curvy",
    skinTone: "Medium",
    ethnicity: "African",
    phone: "0723345612",
    modelLevel: "VIP",
    reviews: 142,
    priceInCall: 110,
    priceOutCall: 130,
    servicesOffered: [
      "OWO (Oral without condom)",
      "O-Level (Oral sex)",
      "CIM (Come in mouth)",
      "COF (Come on face)",
      "COB (Come on body)",
      "Swallow",
      "DFK (deep French kissing)",
      "A-Level (Anal sex)",
      "Anal Rimming (analingus)",
      "69 (69 sex position) - Reverse oral & face sitting",
      "Striptease - lap dance & spanking",
      "Erotic massage (incl. Nuru)",
      "Golden shower (Watersports)",
      "Couples (Group sex)",
      "GFE (Girlfriend experience)",
      "Threesome",
      "Fetishism",
      "Sex toys & Dildo vibrators",
    ],
    description:
      "I'm 24 years old, simple and natural girl, with a body that is voluptuous and curvy, and a personality that is charming and passionate. I came very recently into this field in order to supplement my earnings. When it comes to the integrity of my service, I ensure that you are fully satisfied, where you can freely communicate your needs, based on which I can customise our session. ADVANCE PAYMENT IS MANDATORY FOR VIDEO CALL VERIFICATION WITHOUT ADVANCE DON'T ASK VIDEO CALL VERIFICATION, PLEASE.",
  },
  {
    id: 5,
    name: "Lynn",
    image: images.Image6,
    rating: 4.9,
    location: "Karen",
    age: 28,
    height: "5ft 9in",
    bodyType: "Slim Thick",
    skinTone: "Light Brown",
    ethnicity: "African",
    phone: "0701234589",
    modelLevel: "Elite",
    reviews: 283,
    priceInCall: 180,
    priceOutCall: 200,
    servicesOffered: [
      "OWO (Oral without condom)",
      "O-Level (Oral sex)",
      "CIM (Come in mouth)",
      "COF (Come on face)",
      "COB (Come on body)",
      "Swallow",
      "DFK (deep French kissing)",
      "A-Level (Anal sex)",
      "Anal Rimming (analingus)",

      "Erotic massage (incl. Nuru)",
      "Golden shower (Watersports)",
      "Couples (Group sex)",
      "GFE (Girlfriend experience)",
      "Threesome",
      "Fetishism",
      "Sex toys & Dildo vibrators",
    ],
    description:
      "I'm 24 years old, simple and natural girl, with a body that is voluptuous and curvy, and a personality that is charming and passionate. I came very recently into this field in order to supplement my earnings. When it comes to the integrity of my service, I ensure that you are fully satisfied, where you can freely communicate your needs, based on which I can customise our session. ADVANCE PAYMENT IS MANDATORY FOR VIDEO CALL VERIFICATION WITHOUT ADVANCE DON'T ASK VIDEO CALL VERIFICATION, PLEASE.",
  },
  {
    id: 6,
    name: "Sasha",
    image: images.Image5,
    rating: 4.4,
    location: "Lavington",
    age: 25,
    height: "5ft 5in",
    bodyType: "Petite",
    skinTone: "Fair",
    ethnicity: "Mixed",
    phone: "0745567834",
    modelLevel: "Premium",
    reviews: 98,
    priceInCall: 90,
    priceOutCall: 110,
    servicesOffered: [
      "OWO (Oral without condom)",
      "O-Level (Oral sex)",
      "CIM (Come in mouth)",
      "COF (Come on face)",
      "COB (Come on body)",
      "Swallow",
      "DFK (deep French kissing)",
      "A-Level (Anal sex)",
      "Anal Rimming (analingus)",
      "69 (69 sex position) - Reverse oral & face sitting",
      "Striptease - lap dance & spanking",
      "Erotic massage (incl. Nuru)",
      "Golden shower (Watersports)",
      "Couples (Group sex)",
      "GFE (Girlfriend experience)",
      "Threesome",
      "Fetishism",
      "Sex toys & Dildo vibrators",
    ],
    description:
      "I'm 24 years old, simple and natural girl, with a body that is voluptuous and curvy, and a personality that is charming and passionate. I came very recently into this field in order to supplement my earnings. When it comes to the integrity of my service, I ensure that you are fully satisfied, where you can freely communicate your needs, based on which I can customise our session. ADVANCE PAYMENT IS MANDATORY FOR VIDEO CALL VERIFICATION WITHOUT ADVANCE DON'T ASK VIDEO CALL VERIFICATION, PLEASE.",
  },
  {
    id: 7,
    name: "Ivy",
    image: images.Image7,
    rating: 4.3,
    location: "Kileleshwa",
    age: 27,
    height: "5ft 7in",
    bodyType: "Slim",
    skinTone: "Dark Brown",
    ethnicity: "African",
    phone: "0792345681",
    modelLevel: "Standard",
    reviews: 75,
    priceInCall: 85,
    priceOutCall: 105,
    servicesOffered: [
      "OWO (Oral without condom)",
      "O-Level (Oral sex)",
      "CIM (Come in mouth)",
      "COF (Come on face)",
      "COB (Come on body)",
      "Swallow",
      "DFK (deep French kissing)",
      "A-Level (Anal sex)",
      "Anal Rimming (analingus)",
      "69 (69 sex position) - Reverse oral & face sitting",
      "Striptease - lap dance & spanking",
      "Erotic massage (incl. Nuru)",
      "Golden shower (Watersports)",

      "Threesome",
      "Fetishism",
      "Sex toys & Dildo vibrators",
    ],
    description:
      "I'm 24 years old, simple and natural girl, with a body that is voluptuous and curvy, and a personality that is charming and passionate. I came very recently into this field in order to supplement my earnings. When it comes to the integrity of my service, I ensure that you are fully satisfied, where you can freely communicate your needs, based on which I can customise our session. ADVANCE PAYMENT IS MANDATORY FOR VIDEO CALL VERIFICATION WITHOUT ADVANCE DON'T ASK VIDEO CALL VERIFICATION, PLEASE.",
  },
  {
    id: 8,
    name: "Maya",
    image: images.Image2,
    rating: 4.8,
    location: "Ngong Road",
    age: 23,
    height: "5ft 8in",
    bodyType: "Athletic",
    skinTone: "Medium Brown",
    ethnicity: "African",
    phone: "0717882345",
    modelLevel: "VIP",
    reviews: 201,
    priceInCall: 130,
    priceOutCall: 150,
    servicesOffered: [
      "OWO (Oral without condom)",
      "O-Level (Oral sex)",
      "CIM (Come in mouth)",
      "COF (Come on face)",
      "COB (Come on body)",
      "Swallow",
      "DFK (deep French kissing)",
      "A-Level (Anal sex)",
      "Anal Rimming (analingus)",
      "69 (69 sex position) - Reverse oral & face sitting",
      "Striptease - lap dance & spanking",
      "Erotic massage (incl. Nuru)",
      "Golden shower (Watersports)",
      "Couples (Group sex)",
      "GFE (Girlfriend experience)",
      "Threesome",
      "Fetishism",
      "Sex toys & Dildo vibrators",
    ],
    description:
      "I'm 24 years old, simple and natural girl, with a body that is voluptuous and curvy, and a personality that is charming and passionate. I came very recently into this field in order to supplement my earnings. When it comes to the integrity of my service, I ensure that you are fully satisfied, where you can freely communicate your needs, based on which I can customise our session. ADVANCE PAYMENT IS MANDATORY FOR VIDEO CALL VERIFICATION WITHOUT ADVANCE DON'T ASK VIDEO CALL VERIFICATION, PLEASE.",
  },
  {
    id: 9,
    name: "Talia",
    image: images.Image5,
    rating: 4.5,
    location: "Ruaka",
    age: 24,
    height: "5ft 6in",
    bodyType: "Curvy",
    skinTone: "Caramel",
    ethnicity: "African",
    phone: "0799988765",
    modelLevel: "Premium",
    reviews: 165,
    priceInCall: 115,
    priceOutCall: 135,
    servicesOffered: [
      "OWO (Oral without condom)",
      "O-Level (Oral sex)",
      "CIM (Come in mouth)",
      "COF (Come on face)",
      "COB (Come on body)",
      "Swallow",
      "DFK (deep French kissing)",
      "A-Level (Anal sex)",
      "Anal Rimming (analingus)",
      "69 (69 sex position) - Reverse oral & face sitting",
      "Striptease - lap dance & spanking",
      "Erotic massage (incl. Nuru)",
      "Golden shower (Watersports)",
      "Couples (Group sex)",
      "GFE (Girlfriend experience)",
      "Threesome",
      "Fetishism",
      "Sex toys & Dildo vibrators",
    ],
    description:
      "I'm 24 years old, simple and natural girl, with a body that is voluptuous and curvy, and a personality that is charming and passionate. I came very recently into this field in order to supplement my earnings. When it comes to the integrity of my service, I ensure that you are fully satisfied, where you can freely communicate your needs, based on which I can customise our session. ADVANCE PAYMENT IS MANDATORY FOR VIDEO CALL VERIFICATION WITHOUT ADVANCE DON'T ASK VIDEO CALL VERIFICATION, PLEASE.",
  },
  {
    id: 10,
    name: "Zuri",
    image: images.Image4,
    rating: 4.9,
    location: "Runda",
    age: 25,
    height: "5ft 9in",
    bodyType: "Hourglass",
    skinTone: "Light",
    ethnicity: "African",
    phone: "0788123456",
    modelLevel: "Elite",
    reviews: 312,
    priceInCall: 200,
    priceOutCall: 220,
    servicesOffered: [
      "OWO (Oral without condom)",
      "O-Level (Oral sex)",
      "CIM (Come in mouth)",
      "COF (Come on face)",
      "COB (Come on body)",
      "Swallow",
      "DFK (deep French kissing)",
      "A-Level (Anal sex)",
      "Anal Rimming (analingus)",
      "69 (69 sex position) - Reverse oral & face sitting",
      "Striptease - lap dance & spanking",
      "Erotic massage (incl. Nuru)",
      "Golden shower (Watersports)",
      "Couples (Group sex)",
      "GFE (Girlfriend experience)",
      "Threesome",
      "Fetishism",
      "Sex toys & Dildo vibrators",
    ],
    description:
      "I'm 24 years old, simple and natural girl, with a body that is voluptuous and curvy, and a personality that is charming and passionate. I came very recently into this field in order to supplement my earnings. When it comes to the integrity of my service, I ensure that you are fully satisfied, where you can freely communicate your needs, based on which I can customise our session. ADVANCE PAYMENT IS MANDATORY FOR VIDEO CALL VERIFICATION WITHOUT ADVANCE DON'T ASK VIDEO CALL VERIFICATION, PLEASE.",
  },
  {
    id: 11,
    name: "Nancy",
    image: images.Image6,
    rating: 4.9,
    location: "Lang'ata",
    age: 25,
    height: "5ft 9in",
    bodyType: "Hourglass",
    skinTone: "Light",
    ethnicity: "African",
    phone: "0788123456",
    modelLevel: "Elite",
    reviews: 312,
    priceInCall: 200,
    priceOutCall: 220,
    servicesOffered: [
      "OWO (Oral without condom)",
      "O-Level (Oral sex)",
      "CIM (Come in mouth)",
      "COF (Come on face)",
      "COB (Come on body)",
      "Swallow",
      "DFK (deep French kissing)",
      "A-Level (Anal sex)",
      "Anal Rimming (analingus)",
      "69 (69 sex position) - Reverse oral & face sitting",
      "Striptease - lap dance & spanking",
      "Erotic massage (incl. Nuru)",
      "Golden shower (Watersports)",
      "Couples (Group sex)",
      "GFE (Girlfriend experience)",
      "Threesome",
      "Fetishism",
      "Sex toys & Dildo vibrators",
    ],
    description:
      "I'm 24 years old, simple and natural girl, with a body that is voluptuous and curvy, and a personality that is charming and passionate. I came very recently into this field in order to supplement my earnings. When it comes to the integrity of my service, I ensure that you are fully satisfied, where you can freely communicate your needs, based on which I can customise our session. ADVANCE PAYMENT IS MANDATORY FOR VIDEO CALL VERIFICATION WITHOUT ADVANCE DON'T ASK VIDEO CALL VERIFICATION, PLEASE.",
  },
  {
    id: 12,
    name: "Kamama",
    image: images.Image7,
    rating: 4.9,
    location: "Runda",
    age: 25,
    height: "5ft 9in",
    bodyType: "Hourglass",
    skinTone: "Light",
    ethnicity: "African",
    phone: "0788123456",
    modelLevel: "Elite",
    reviews: 312,
    priceInCall: 200,
    priceOutCall: 220,
    servicesOffered: [
      "OWO (Oral without condom)",
      "O-Level (Oral sex)",
      "CIM (Come in mouth)",
      "COF (Come on face)",
      "COB (Come on body)",
      "Swallow",
      "DFK (deep French kissing)",
      "A-Level (Anal sex)",
      "Anal Rimming (analingus)",
      "69 (69 sex position) - Reverse oral & face sitting",
      "Striptease - lap dance & spanking",
      "Erotic massage (incl. Nuru)",
      "Golden shower (Watersports)",
      "Couples (Group sex)",
      "GFE (Girlfriend experience)",
      "Threesome",
      "Fetishism",
      "Sex toys & Dildo vibrators",
    ],
    description: "",
  },
];

export type Model = {
  id: number;
  name: string;
  image: StaticImageData;
  rating: number;
  location: string;
  age: number;
  height: string;
  bodyType: string;
  skinTone: string;
  ethnicity: string;
  phone: string;
  modelLevel: string;
  reviews: number;
  priceInCall: number;
  priceOutCall: number;
  description: string;
  servicesOffered: string[];
};

export const Reviews: Review[] = [
  {
    id: 1,
    modelName: "Cassandra",
    starsCount: "4",
    reviewMessage:
      "This guy will blow your brains out plus I never knew that I’ll meet such a snack on this platform.",
    reviewDate: "2025-11-18",
    reviewerName: "John Doe",
  },
  {
    id: 2,
    modelName: "Linda",
    starsCount: "4",
    reviewMessage:
      "This girl is so hot and she is so kind. She is so sweet and she is so beautiful. She is so talented and she is so beautiful.",
    reviewDate: "2025-11-18",
    reviewerName: "Anonymus",
  },
  {
    id: 3,
    modelName: "Lavender",
    starsCount: "4",
    reviewMessage:
      "This girl is so hot and she is so kind. She is so sweet and she is so beautiful. She is so talented and she is so beautiful.",
    reviewDate: "2025-11-18",
    reviewerName: "Lavender lover",
  },
  {
    id: 4,
    modelName: "Tess",
    starsCount: "5",
    reviewMessage:
      "Absolutely stunning and incredibly fun to talk to. Her vibe is unmatched. Worth every second!",
    reviewDate: "2025-11-19",
    reviewerName: "Michael K.",
  },
  {
    id: 5,
    modelName: "Amina",
    starsCount: "5",
    reviewMessage:
      "Elegant, respectful, and a great conversationalist. Had an amazing time and would definitely recommend.",
    reviewDate: "2025-11-20",
    reviewerName: "Chris P.",
  },
  {
    id: 6,
    modelName: "Nala",
    starsCount: "4",
    reviewMessage:
      "Very friendly and looks even better in person. She made the experience feel natural and relaxed.",
    reviewDate: "2025-11-21",
    reviewerName: "Derrick",
  },
  {
    id: 7,
    modelName: "Rihanna",
    starsCount: "5",
    reviewMessage:
      "Pure class. Good communication, punctual, and absolutely gorgeous. Highly recommended.",
    reviewDate: "2025-11-21",
    reviewerName: "Alpha",
  },
  {
    id: 8,
    modelName: "Maya",
    starsCount: "3",
    reviewMessage:
      "She was polite and easy to talk to. The session was decent but could’ve been better with clearer communication beforehand.",
    reviewDate: "2025-11-22",
    reviewerName: "Kevin O.",
  },
  {
    id: 9,
    modelName: "Zuri",
    starsCount: "5",
    reviewMessage:
      "Energy on point! She made the whole experience memorable and comfortable. Will definitely see her again.",
    reviewDate: "2025-11-23",
    reviewerName: "Jay Jay",
  },
  {
    id: 10,
    modelName: "Bella",
    starsCount: "4",
    reviewMessage:
      "She has a warm personality and an amazing smile. Looked even better than her profile photos.",
    reviewDate: "2025-11-24",
    reviewerName: "Moses",
  },
];

export interface Review {
  id: number;
  modelName: string;
  starsCount: string;
  reviewMessage: string;
  reviewDate: string;
  reviewerName: string;
}
